### PR TITLE
Use go modules

### PR DESCRIPTION
**Pull request by horjulf**
Replaces `dep` with Go modules.

### CODE REVIEW

**Comment by mathyourlife-fitbit** [comment]
Mind updating the Development section of the README.md to match the new tooling?

**Comment by horjulf** [comment]
@mathyourlife-fitbit done, thanks.

**Comment by horjulf** [comment]
CI failed for go 1.11, unsure why, maybe a rerun would be successful.
I don't think theres any reason to keep 1.11 tho, @mathyourlife-fitbit what do you think of removing 1.11 ?

**Comment by SpamapS** [comment]
Could you explain why this change would be a good thing? There's no problem statement, no issue linked, nothing to tell me, a casual observer, why this change is desirable.

**Comment by DeviaVir** [comment]
@SpamapS your criticism is justified.  Going off of https://blog.golang.org/using-go-modules:
> Go modules are the future of dependency management in Go.
I assumed this gets us back to "cool kids on the block" status.

**Comment by DeviaVir** [comment]
superseded by https://github.com/DeviaVir/terraform-provider-gsuite/pull/73

**Pull request closed without merging**
