### PR TITLE
Adding member list to solve issues with consistency

### PR DESCRIPTION
**Pull request by Madankapoor**
To allow adding multiple members to a group using a list instead of set.

1. Helps in integration with terraform modules with GCP 
2. Allows consistent creation of users without any errors as an alternative for using count and gsuite_group_member

### CODE REVIEW

**Comment by psalaberria002** [comment]
Adding an extra resource type seems unecessary. What problem does this new resource solve? The members set in gsuite_group_members with dynamic blocks gives you all the flexibility you need.

**Comment by Madankapoor** [comment]
Terraform 0.11 doesn't support for each and dynamic. Multiple projects still run on terraform 0.11. I have a dependency on components converged on terraform 0.11.  To avoid approaches like below which cause issues on multiple converges. 
`
resource "gsuite_group_member" "group_members" {
  group = "${lookup(var.group_members[count.index],"group",var.email)}"
  email = "${lookup(var.group_members[count.index],"email")}"
  role  = "${lookup(var.group_members[count.index],"role","MEMBER")}" # OWNER/MANAGER/MEMBER
  count = "${length(var.group_members)}"
}
`

**Comment by Karthik-13** [comment]
I'm still using Terraform v0.11 for various reasons. Will this PR be merged? It would be pretty useful for my usecases.

**Comment by DeviaVir** [comment]
Wouldn't it be easier to add a schema element to the existing `gsuite_members`, say `list` or `member_list` and apply that same logic there? I won't add a new resource that does the same thing slightly different.

**Comment by Madankapoor** [comment]
Initially, even I had the same idea. I even implemented it then I found out that it was confusing why would we have a single resource with two attributes to specify members. Then I felt it was better to have two resources one named as ```gsuite_group_member_list``` and ```gsuite_group_members``` which makes it easier to understand. 
Like we have two resources already ```gsuite_group_member``` to add a single member and then ```gsuite_group_members``` to add a set of members. extending this approach with ```gsuite_group_member_list``` to add a list of members. So I am applying a logical open-close principle I am only extending the existing logic without modification of existing  code which in turn would reduce the number of issues and make maintenance easier

**Pull request closed without merging**
