### PR TITLE
Implement `custom_schema` on gsuite_user resources

### PR DESCRIPTION
**Pull request by opalmer**
This is a follow-on to PR #41 and issue #28 and it implements the ability to set custom attributes on `gsuite_user` resources (closing #45), see [examples/user-with-custom-schema/user-with-custom-schema.tf](https://github.com/opalmer/terraform-provider-gsuite/blob/user-custom-schema/examples/user-with-custom-schema/user-with-custom-schema.tf) for a complete example.

In addition in this PR I have:

- Fixed a couple of bugs I found in `resource_user_schema.go` while testing.
- Removed any unused functions or variables.
- Run `terraform fmt` on the examples / `goimports` and `go fmt` on the source code.
- Minor build updates (add Go 1.10, remove `sudo: required` [[see blog post](https://changelog.travis-ci.com/the-container-based-build-environment-is-fully-deprecated-84517)])
- Updated `GOVERSION` in the makefile to 1.11 from 1.11.3 (see commit 61995c8ed6b2c3eecbad6f1e45257be6b00c589f for additional information)

I'll be happy to move the above changes to another PR or open an issue to discuss instead if that's preferred.

Testing wise, I've been using the example mentioned above on an existing user within my gsuite domain without issues but like like time I wouldn't mind a second set of eyes before this merges just to make sure the bases are covered.

### CODE REVIEW

**Comment by DeviaVir** [comment]
@opalmer I took your branch for a spin and ran into the following:
```
* gsuite_user.user: Error creating user: googleapi: Error 400: Invalid Input: custom_schema, invalid
2019/01/09 11:47:56 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* gsuite_user.user: Error creating user: googleapi: Error 400: Invalid Input: custom_schema, invalid
2019/01/09 11:47:56 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: Error applying plan:

1 error(s) occurred:

* gsuite_user.user: 1 error(s) occurred:

* gsuite_user.user: Error creating user: googleapi: Error 400: Invalid Input: custom_schema, invalid
```

I copied your example and changed the domain, this should've worked, no?

**Comment by opalmer** [comment]
Yeah, it did for me at least :(

Could you send the steps to reproduce and maybe a log with trace output (feel free to share OOB if you'd prefer).

**Comment by opalmer** [comment]
@DeviaVir I may have figured out the problem. If you were copying the example I made you'd get a 400 error because I was applying `data.gsuite_user_attributes.test` for both `test-schema` and `additional-details` which results in:

```
Error: Error applying plan:

1 error(s) occurred:

* gsuite_user.user: 1 error(s) occurred:

* gsuite_user.user: Error updating user: {"error":{"errors":[{"domain":"global","reason":"invalid","message":"Invalid Input: custom_schema"}],"code":400,"message":"Invalid Input: custom_schema"}}: googleapi: Error 400: Invalid Input: custom_schema, invalid
```

In b28e519aacc240f52b75bc12dc2ae604ac5b8a0d in fixed the broken example which seems to have fixed the 400 error for me and allowed the apply to proceed. Assuming you were using the example, this should be working now (sorry....I should have tested using the example instead of making my own on the side) 

Does this resolve the error for you @DeviaVir ?

**Comment by DeviaVir** [comment]
@opalmer apologies I didn't get back to you sooner. I verified your last commit fixes it and allowed me to create this user with the user schemas.

I'll approve and merge.

Thanks for your contribution @opalmer!

**Pull request merged**
